# see: https://docs.travis-ci.com/user/languages/r

language: r
warnings_are_errors: true
sudo: required

env:
 global:
   - CRAN: http://cran.rstudio.com

notifications:
  email:
    on_success: tnk.yasutaka@gmail.com
    on_failure: tnk.yasutaka@gmail.com

# r_github_packages for development version dependencies
# r_binary_packages for faster build by precompiled Ubuntu packages
